export const PROGRAMMING_FILTER_CATEGORIES = {
  'Data Structures': [
    'Array',
    'Dynamic Array',
    'String',
    'Matrix',
    'Linked List',
    'Doubly Linked List',
    'Stack',
    'Queue',
    'Deque',
    'Circular Buffer',
    'Hash Map',
    'Hash Set',
    'Hash Table',
    'Bloom Filter',
    'Heap',
    'Priority Queue',
    'Trie',
    'Binary Tree',
    'Binary Search Tree',
    'AVL Tree',
    'Red-Black Tree',
    'Segment Tree',
    'Fenwick Tree',
    'Disjoint Set Union',
    'Graph',
    'Directed Graph',
    'DAG',
    'Adjacency List',
    'Adjacency Matrix',
  ],
  Sorting: [
    'Sorting',
    'Bubble Sort',
    'Selection Sort',
    'Insertion Sort',
    'Merge Sort',
    'Quick Sort',
    'Heap Sort',
    'Counting Sort',
    'Radix Sort',
    'Bucket Sort',
    'Topological Sort',
  ],
  Searching: [
    'Searching',
    'Linear Search',
    'Binary Search',
    'Depth-First Search',
    'Breadth-First Search',
    'Bidirectional Search',
    'Backtracking',
    'Sliding Window',
    'Two Pointers',
    'Fast and Slow Pointers',
    'Meet in the Middle',
  ],
  'Algorithms and Techniques': [
    'Recursion',
    'Dynamic Programming',
    'Greedy',
    'Divide and Conquer',
    'Memoization',
    'Prefix Sum',
    'Difference Array',
    'Monotonic Stack',
    'Monotonic Queue',
    'Interval Problems',
    'Sweep Line',
    'Bit Manipulation',
    'Bitmask',
    'Math',
    'Number Theory',
    'Combinatorics',
    'Probability',
    'Geometry',
    'Randomized Algorithms',
  ],
  'Graphs and Networks': [
    'Shortest Path',
    'Dijkstra',
    'Bellman-Ford',
    'Floyd-Warshall',
    'Minimum Spanning Tree',
    'Kruskal',
    'Prim',
    'Union Find',
    'Cycle Detection',
    'Connected Components',
    'Strongly Connected Components',
    'Bipartite Graph',
    'Network Flow',
  ],
  'Programming Concepts': [
    'Object-Oriented Programming',
    'Functional Programming',
    'Concurrency',
    'Parallelism',
    'Caching',
    'Parsing',
    'String Matching',
    'Regular Expressions',
    'API Design',
    'System Design',
    'Databases',
    'SQL',
    'Testing',
    'Debugging',
    'Time Complexity',
    'Space Complexity',
  ],
} as const;

export const PROGRAMMING_FILTERS = Object.values(PROGRAMMING_FILTER_CATEGORIES).flat();
